#- name: Ensure group "{{ global.group }}" exists
#  group: name={{ item.name }} gid={{ item.gid }} state=present system={{ item.system | default(omit) }}
#  with_items:
#    - "{{ add_groups }}"

#- name: Ensure user "{{ global.user }}" exists
#  user: name={{ item.name }} uid={{ item.uid }} comment={{ item.comment }} group={{ item.group }} shell=/bin/bash system={{ item.system | default(omit) }} state=present
#  with_items:
#    - "{{ add_users }}"

- name: Ensure work dir
  file: path="{{ item }}" state=directory owner={{ global.rc_user}} group={{ global.rc_group }} mode=0755
  with_items:
    - "{{ global.base_path }}"
    - "{{ global.app_path }}"
    - "{{ global.logs_path }}"
    - "{{ global.data_path }}"
    - "{{ global.tmp_path }}"
    - "{{ global.backup_path }}"
