---
elasticsearch_host: "{{ ansible_host }}"
elasticsearch_http_port: 9200
elasticsearch_tcp_port: 9300

inst_name: "es"
es_name: "{{ inst_name }}"
es_version: 5.6.5
es_package: "{{ package_path }}/elasticsearch-{{ es_version }}.tar.gz"
es_path: "{{ app_path }}/{{ es_name }}"

data_dir: "{{ data_path }}/{{ es_name }}"
log_dir: "{{ logs_path }}/{{ es_name }}"
elasticsearch_cluster_name: "prod"

elasticsearch_jvm: "1g"
es_hosts: []
es_user: "rcloud"
es_group: "rcloud"
elasticsearch_user: "{{ es_user }}" 
elasticsearch_group: "{{ es_group }}"
