- name: Override variables for MySQL.
  set_fact:
    mysql_daemon: mysql
    mysql_packages: ['mysql-server']
    mysql_log_error: "{{ mysql_log_dir }}/mysqld.err"
    mysql_syslog_tag: mysqld
    mysql_pid_file: "{{ mysql_path }}/mysqld.pid"
    mysql_socket: "{{ mysql_path }}/mysql.sock"
  when: ansible_architecture == 'x86_64'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"