# Here We Create The Group and User
- name: debug time
  debug: var=ansible_date_time.iso8601
  ignore_errors: yes

- name: Create Nginx Group
  group:
    name: "{{ nginx_group }}"
    state: present

- name: Create Nginx user
  user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    comment: "Nginx Service User"

- name: unzip nginx package
  unarchive:
    src: "{{ nginx_package }}"
    dest: "{{ global.tmp_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755

- name: Copy Nginx
  command: cp -Ra "{{ global.tmp_path }}/nginx" "{{ nginx_path }}"

- name: Change Nginx ownership
  file:
    path: "{{ nginx_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory
    recurse: yes
    mode: 0755

- name: Ensure nginx vhost dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_items: 
    - "{{ nginx_vhost_path }}"
    - "{{ nginx_conf_path }}"
    - "{{ nginx_logpath }}"

- name: Add nginx service configured.
  template:
    src: nginx.service.j2
    dest: "{{ global.conf_path }}/{{ nginx_name }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
  notify: restart nginx

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_path }}/conf/nginx.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
  notify:
    - restart nginx

- name: Ensure nginx service is present
  supervisorctl:
    name: "{{ nginx_name }}"
    state: present
    supervisorctl_path: "{{ global.supervisorctl }}"

- name: Ensure nginx_vhost_path exists.
  file:
    path: "{{ nginx_vhost_path }}"
    state: directory
  notify: restart nginx

- name: Add rce vhost config file
  vars:
    name: 'rce'
  template:
    src: vhosts.j2
    dest: "{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}"
    mode: 0644
  when: nginx_flag == 'rce'

- name: Add im vhost config file
  vars:
    name: 'im'
  template:
    src: vhosts_im.j2
    dest: "{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}"
    mode: 0644
  when: nginx_flag == 'im'

- name: Add api vhost config file
  vars:
    name: 'api'
  template:
    src: vhosts_api.j2
    dest: "{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}"
    mode: 0644
  when: nginx_flag == 'api'

- name: Add rcx management config file
  vars:
    name: 'mgt'
  template:
    src: vhosts_mgt.j2
    dest: "{{ nginx_vhost_path }}/{{ nginx_vhost_filename }}"
    mode: 0644
  when: nginx_flag == 'mgt'

- name: change path owner
  file:
    path: "{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory
    recurse: yes
  with_items: 
    - "{{ nginx_path }}"
    - "{{ nginx_logpath }}"

- name: Ensure nginx is running
  supervisorctl:
    name: "{{ nginx_name }}"
    state: restarted
    supervisorctl_path: "{{ global.supervisorctl }}"
