- hosts: all
  roles:
  - role: install-python
    tags: all
  - role: systemconf
    tags: all
  - role: supervisord
    tags: all
  - role: openssl
    tags: all
  - role: jre
    tags: all
  vars: {}
- hosts: im_node1
  roles:
  - role: mysql
    tags: mysql
  vars:
    inst_name: mysql.inst-0
- hosts: im_node1
  roles:
  - role: rcdb
    tags: rcx-rcdb
  vars:
    inst_name: rcx-rcdb.inst-0
    rcdb_port: '8888'
- hosts: im_node1
  roles:
  - role: rcdb
    tags: rcx-rcdb
  vars:
    inst_name: rcx-rcdb.inst-1
    rcdb_port: '8889'
- hosts: im_node1
  roles:
  - role: redis
    tags: redis
  vars:
    inst_name: redis.inst-0
- hosts: im_node1
  roles:
  - role: fastdfs
    tags: fastdfs
  vars:
    inst_name: fastdfs.inst-0
- hosts: im_node1
  roles:
  - role: rcx-db
    tags: rcx-server
  - role: rcx
    tags: rcx-server
  vars:
    common_config:
    - config.xml
    - db-config.xml
    - comcloud_x_imdb.properties
    - log4j2.xml
    configs:
    - admin-http-config.xml
    - api-http-config.xml
    - navi-http-config.xml
    - service-config.xml
    - rcx-cfg.xml
    - restfulhttp-config.xml
    - management.properties
    inst_name: rcx-server.inst-0
    plugins:
      access:
      - config: admin-http-config.xml
        main: rcx.access.http.Bootstrap
        name: rcx.access.http.admin
        path: plugins/rcx.access.http.jar
      - config: api-http-config.xml
        main: rcx.access.http.Bootstrap
        name: rcx.access.http.api
        path: plugins/rcx.access.http.jar
      - config: navi-http-config.xml
        main: rcx.access.http.Bootstrap
        name: rcx.access.http.navi
        path: plugins/rcx.access.http.jar
      - config: service-config.xml
        main: rcx.access.services.Bootstrap
        name: rcx.access.services
        path: plugins/rcx.access.services.jar
      admin:
      - main: rcx.api.configure.Bootstrap
        name: rcx.api.configure
        path: plugins/rcx.api.configure.jar
      api:
      - main: rcx.api.group.Bootstrap
        name: rcx.api.group
        path: plugins/rcx.api.group.jar
      - main: rcx.api.message.Bootstrap
        name: rcx.api.message
        path: plugins/rcx.api.message.jar
      - main: rcx.api.userinfo.Bootstrap
        name: rcx.api.userinfo
        path: plugins/rcx.api.userinfo.jar
      - main: rcx.api.mediacenter.Bootstrap
        name: rcx.api.mediacenter
        path: plugins/rcx.api.mediacenter.jar
      navi:
      - main: rcx.http.navi.Bootstrap
        name: rcx.http.navi
        path: plugins/rcx.http.navi.jar
      restful:
      - main: rcx.api.healthcheck.Bootstrap
        name: rcx.api.healthcheck
        path: plugins/rcx.api.healthcheck.jar
      service:
      - main: rcx.service.broadcast.Bootstrap
        name: rcx.service.broadcast
        path: plugins/rcx.service.broadcast.jar
      - main: rcx.service.fileserverplugin.Bootstrap
        name: rcx.service.fileserverplugin
        path: plugins/rcx.service.fileserverplugin.jar
      - main: rcx.service.group.Bootstrap
        name: rcx.service.group
        path: plugins/rcx.service.group.jar
      - main: rcx.service.historymsg.Bootstrap
        name: rcx.service.historymsg
        path: plugins/rcx.service.historymsg.jar
      - main: rcx.service.message.Bootstrap
        name: rcx.service.message
        path: plugins/rcx.service.message.jar
      - main: rcx.service.messagetransmit.Bootstrap
        name: rcx.service.messagetransmit
        path: plugins/rcx.service.messagetransmit.jar
      - main: rcx.service.pushmediator.Bootstrap
        name: rcx.service.pushmediator
        path: plugins/rcx.service.pushmediator.jar
      - main: rcx.service.relationinfo.Bootstrap
        name: rcx.service.relationinfo
        path: plugins/rcx.service.relationinfo.jar
      - main: rcx.service.richmediaplugin.Bootstrap
        name: rcx.service.richmediaplugin
        path: plugins/rcx.service.richmediaplugin.jar
      - main: rcx.service.upstream.Bootstrap
        name: rcx.service.upstream
        path: plugins/rcx.service.upstream.jar
      - main: rcx.service.userconnection.Bootstrap
        name: rcx.service.userconnection
        path: plugins/rcx.service.userconnection.jar
      - main: rcx.service.usersetting.Bootstrap
        name: rcx.service.usersetting
        path: plugins/rcx.service.usersetting.jar
      - main: rcx.service.userstatus.Bootstrap
        name: rcx.service.userstatus
        path: plugins/rcx.service.userstatus.jar
      - main: rcx.service.monitor.Bootstrap
        name: rcx.service.monitor
        path: plugins/rcx.service.monitor.jar
      - main: rcx.service.mediacenter.Bootstrap
        name: rcx.service.mediacenter
        path: plugins/rcx.service.mediacenter.jar
      - main: rcx.service.templatetransmit.Bootstrap
        name: rcx.service.templatetransmit
        path: plugins/rcx.service.templatetransmit.jar
- hosts: im_node1
  roles:
  - role: rcx-management
    tags: rcx-management
  vars:
    inst_name: rcx-management.inst-0
- hosts: im_node1
  roles:
  - role: zookeeper
    tags: zookeeper
  vars:
    inst_name: zookeeper.inst-0
- hosts: im_node1
  roles:
  - role: nginx
    tags: rcx-nginx
  vars:
    inst_name: rcx-nginx.inst-0
    mgt_servers:
    - '{{ private_ip }}:8094'
    nginx_upstreams:
    - keepalive: 16
      name: mgt
      servers: '{{ mgt_servers }}'
      strategy: ip_hash
