---
inst_name: "rce.redis"
redis_name: "{{ inst_name }}"
redis_package: "{{ global.package_path }}/redis.tar.gz"

install: True

redis_path: "{{ global.app_path }}/{{ inst_name }}"

redis_port: 6379
redis_host: 127.0.0.1
redis_pass: 'wdca@e44ew5'
redis_unixsocket: ''
redis_timeout: 300

redis_loglevel: "notice"
redis_logpath: "{{ global.logs_path }}/{{ redis_name }}"
redis_logfile: "{{ redis_logpath }}/redis-server.log"

redis_databases: 16

# Set to an empty set to disable persistence (saving the DB to disk).
redis_save:
  - 900 1
  - 300 10
  - 60 10000

redis_rdbcompression: "yes"
redis_dbfilename: dump.rdb
redis_dbpath: "{{ global.data_path }}/{{ redis_name }}"

redis_maxmemory: 0
redis_maxmemory_policy: "noeviction"
redis_maxmemory_samples: 5

redis_appendonly: "no"
redis_appendfsync: "everysec"

# Add extra include files for local configuration/overrides.
redis_includes: []
#redis_ensure_dirs: []

#
rc_user: "root"
rc_group: "root"
redis_user: "{{ rc_user }}"
redis_group: "{{ rc_group }}"
