---
inst_name: "rcx-fileserver"
rc_user: "{{ global.rc_user }}"
rc_group: "{{ global.rc_group }}"

rcx_path: "{{ global.app_path }}/{{ inst_name }}"
rcx_logpath: "{{ global.logs_path }}/{{ inst_name }}"

plugins:
  access:
  - {config: storage-config.xml, main: rcx.access.filestorageserver.Bootstrap, name: rcx.access.filestorageserver, path: plugins/rcx.access.filestorageserver.jar}

configs: 
  - storage-config.xml
  - namespace.properties
  - trafficctl.properties
common_config:
  - config.xml
  - log4j2.xml

rcdbs: []

up: 10240
down: 10240

public_ip: "127.0.0.1"
private_ip: "127.0.0.1"
apush_public_host: "{{ public_ip }}"
apush_listen_port: 8089
apush_public_port: 8089

admin_http_port: 8091
navi_http_port: 8082
api_http_port: 8081
#restful_port: 8084

rmtp_public_host: "{{ public_ip }}"
rmtp_private_host: "{{ private_ip }}"
rmtp_listen_port: 8087
rmtp_public_port: 8087
rmtp_private_port: 8087
rmtp_ap_port: 8000
rmtp_ws_listen_port: 8085
rmtp_ws_public_host: "{{ public_ip }}"
rmtp_ws_private_host: "{{ private_ip }}"
rmtp_ws_public_port: 8085
rmtp_ws_private_port: 8085
rmtp_wss_public_host: "{{ public_ip }}"
rmtp_wss_public_port: 8086
rmtp_wss_private_host: "{{ private_ip }}"
rmtp_wss_private_port: 8086

zookeeper_hosts: []
zk_hosts: []

rpc_ip: "{{ ansible_host }}"
rpc_port: 8090

fileserver_path: "{{ global.data_path }}/filestorage/data"
fileserver_port: 8083
virtualNodesNum: 100
isHttpServer: "true"

mysql_port: 4306
mysql_user: 'im'
mysql_password: '1qazCDE#'

mysql_host: '127.0.0.1'
imdb: 'comcloud_x'
cluster: 'clusterCommon'
proxy_platform: 'MiniProgramKeng'
rcx_db: 'rcx_db'
file_expired_day: 18000
id: 1
db_type: 'mysql'
fs: []

storage_port: 23000
tracker_port: 22122

tracker_string: "
    {%- set ips = [] %}
    {%- for host in groups['fastdfs'] %}
    {{- ips.append(dict(id=loop.index, host=host, ip=hostvars[host]['private_ip'], port=tracker_port)) }}
    {%- endfor %}
    {{- ips -}}"

storage_string: "
    {%- set ips = [] %}
    {%- for host in groups['fastdfs'] %}
    {{- ips.append(dict(id=loop.index, host=host, ip=hostvars[host]['private_ip'],  port=storage_port)) }}
    {%- endfor %}
    {{- ips -}}"
