hosts:
  im_node1:
    - ansible_host: 172.29.202.18
    - mysql_server_id: 1
    - mysql_replication_role: master
    - ansible_connection: local
  im_node2:
    - ansible_host: 172.29.202.30
    - mysql_server_id: 2
    - mysql_replication_role: slave
  im_node3:
    - ansible_host: 172.29.202.6
groups:
  rcx_rcdb:
    - im_node2
    - im_node3
  rcx_server:
    - im_node2
    - im_node3
  rcx_management:
    - im_node1
  zookeeper:
    - im_node1
    - im_node2
    - im_node3
  rcx_nginx:
    - im_node1
  redis:
    - im_node1
    - im_node2
    - im_node3
  fastdfs:
    - im_node2
    - im_node3
vars:
  global:
    base_path: /data
  mysql:
    mysql_host: "{{ hostvars[groups['mysql'][0]]['ansible_host'] }}"
    mysql_replication_master: '{{ mysql_host }}'
  rcx_rcdb:
    rcdb_nums: 2
  rcx_server:
    admin_http_port: 8083
    api_http_port: 8081
    apush_public_port: 8070
    navi_http_port: 8082
    rmtp_public_port: 8043
    rmtp_ws_public_port: 8085

