# Generated by Django 2.2.6 on 2020-04-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='业务线名称')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='是否激活')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='部署顺序')),
                ('description', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '业务线信息表',
                'verbose_name_plural': '业务线信息表',
                'db_table': 'weops_business',
            },
        ),
        migrations.CreateModel(
            name='ConfigMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('business', models.CharField(blank=True, default='rcx', max_length=12, verbose_name='业务线')),
                ('level', models.CharField(choices=[('H', 'host'), ('HG', 'group'), ('G', 'global'), ('R', 'role')], default='G', max_length=8, verbose_name='配置项级别')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='配置项标题')),
                ('key', models.CharField(blank=True, max_length=32, null=True, verbose_name='配置项key')),
                ('value', models.CharField(blank=True, max_length=32, null=True, verbose_name='配置项value')),
                ('isBase', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否是基础配置')),
                ('comment', models.CharField(blank=True, max_length=32, null=True, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '配置信息表',
                'verbose_name_plural': '配置信息表',
                'db_table': 'weops_configmap',
            },
        ),
        migrations.CreateModel(
            name='DeployModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('server_name', models.CharField(blank=True, max_length=16, verbose_name='服务名称')),
                ('hostname', models.CharField(blank=True, max_length=32, verbose_name='主机名')),
                ('business', models.CharField(blank=True, max_length=16, verbose_name='业务线')),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='私有IP')),
                ('external_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公有IP')),
                ('cpu', models.CharField(blank=True, max_length=8, null=True, verbose_name='CPU核数')),
                ('mem', models.CharField(blank=True, max_length=8, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=8, null=True, verbose_name='磁盘空间')),
                ('instance_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='实例名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='说明')),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'STARTED'), (1, 'PENDING'), (-1, 'FAILED'), (2, 'SUCCSESS'), (3, 'RETRY')], default=0, verbose_name='部署状态')),
            ],
            options={
                'verbose_name': '部署模型',
                'verbose_name_plural': '部署模型表',
                'db_table': 'weops_deploy_models',
            },
        ),
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('business', models.CharField(blank=True, max_length=8, verbose_name='业务线')),
                ('key', models.CharField(blank=True, max_length=16, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=16, verbose_name='value')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '全局变量',
                'verbose_name_plural': '全局变量表',
                'db_table': 'weops_global_vars',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='服务名称')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='部署顺序')),
                ('description', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='描述信息')),
                ('role', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色列表')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='deploy.BusinessLine', verbose_name='关联的业务线')),
            ],
            options={
                'verbose_name': '服务信息表',
                'verbose_name_plural': '服务信息表',
                'db_table': 'weops_service',
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.CreateModel(
            name='ResourceConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('cpu', models.CharField(blank=True, default='8c', max_length=8, verbose_name='CPU核数')),
                ('mem', models.CharField(blank=True, default='16g', max_length=12, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='100g', max_length=12, null=True, verbose_name='磁盘空间')),
                ('num', models.SmallIntegerField(blank=True, null=True, verbose_name='主机数量')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_line', to='deploy.BusinessLine')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svc', to='deploy.Service')),
            ],
            options={
                'verbose_name': '资源配置表',
                'verbose_name_plural': '资源配置表',
                'db_table': 'weops_resource_conf',
            },
        ),
    ]
